version: "3"
services:
  base:
    build: .
    volumes:
      - .:/code
    command: 'false'

  web:
    extends:
      service: base
    command: flask run --host=0.0.0.0
    env_file:
      - env_file
    ports:
      - "5000:5000"
    depends_on:
      - db

  celery:
    extends:
      service: base
    command: /bin/bash celery_entry.sh
    env_file:
      - env_file
    depends_on:
      - redis

  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379/tcp"

  db:
    image: postgres:10
    restart: always
    env_file:
      - env_file
    ports:
      - "5432:5432"

  migrations:
    extends:
      service: base
    env_file:
      - env_file
    command: flask db upgrade
    depends_on:
      - db

  example_data_loader:
    extends:
      service: base
    env_file:
      - env_file
    command: python load_example_data.py
    depends_on:
      - db