version: "3"
services:
  api_gateway:
    container_name: api_gateway
    restart: always
    build: .
    env_file:
      - env_file
    ports:
      - "8000:8000"
    command: gunicorn --config gunicorn.conf.py wsgi:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api_gateway
