version: "3"
services:
  api_gateway:
    container_name: api_gateway
    restart: always
    build: .
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api_gateway
